# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('view_account', 'Can view account'),), 'verbose_name': 'Checking account', 'verbose_name_plural': 'Checking accounts'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'permissions': (('view_contract', 'Can view contract'),), 'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterModelOptions(
            name='credit',
            options={'permissions': (('view_credit', 'Can view credit'),), 'verbose_name': 'Credit', 'verbose_name_plural': 'Credits'},
        ),
        migrations.AlterModelOptions(
            name='credittemplate',
            options={'permissions': (('view_credittemplate', 'Can view credit template'),), 'verbose_name': 'Credit templates', 'verbose_name_plural': 'Credit templates'},
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'permissions': (('view_deposit', 'Can view deposit'),), 'verbose_name': 'Deposit', 'verbose_name_plural': 'Deposits'},
        ),
        migrations.AlterModelOptions(
            name='deposittemplate',
            options={'permissions': (('view_deposittemplate', 'Can view deposit template'),), 'verbose_name': 'Deposit templates', 'verbose_name_plural': 'Deposit templates'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('view_product', 'Can view product'),), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('view_transaction', 'Can view transaction'),), 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='credittemplate',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposittemplate',
            name='cancellation_condition',
            field=models.IntegerField(choices=[(0, b'Anytime'), (1, b'Anytime with lossy'), (2, b'Only after end of term')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposittemplate',
            name='indexing',
            field=models.IntegerField(choices=[(0, b'Yearly'), (1, b'Daily'), (2, b'Monthly'), (3, b'Quarterly')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposittemplate',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
