# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 12:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20161118_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittemplate',
            name='percentage',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='deposittemplate',
            name='percentage',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
