# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20161119_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittemplate',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='deposittemplate',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
