# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20161120_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposittemplate',
            name='cancellation_condition',
        ),
        migrations.AddField(
            model_name='deposittemplate',
            name='defeasans',
            field=models.IntegerField(choices=[(0, 'Anytime'), (1, 'Anytime with loss'), (2, 'Only after end of term')], default=1),
        ),
    ]
