db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=jupiter
    - POSTGRES_USER=jupiter
    - PGPORT=6000
  ports:
    - "6000:6000"

backend:
  image: jupiterapp/backend
  ports:
    - "8000:8000"
  environment:
    - DB_PASSWORD=jupiter
    - DB_USER=jupiter
    - DB_HOST=db
    - DB_PORT=6000
    - MIGRATE=true
    - COLLECTSTATIC=true
    - TEST=false
    - RUNSERVER=true
    - SLEEP=false
    - SENDGRID_API_KEY=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
  links:
    - db:db

frontend:
  image: jupiterapp/frontend
  ports:
    - "80:80"
    - "443:443"
  links:
    - backend:backend
