db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=jupiter
    - POSTGRES_USER=jupiter
    - PGPORT=6000
  ports:
    - "6000:6000"

backend:
  image: jupiterapp/backend
  ports:
    - "8000:8000"
  volumes:
    - ./backend:/backend
  links:
    - db:db

frontend:
  image: jupiterapp/frontend
  ports:
    - "80:80"
  volumes:
    - ./frontend/data/:/frontend/data/
    - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./frontend/nginx/conf.d/:/etc/nginx/conf.d/
  links:
    - backend:backend