db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=jupiter
    - POSTGRES_USER=jupiter
    - PGPORT=6000
  ports:
    - "6000:6000"

backend:
  image: jupiterapp/backend
  ports:
    - "8000:8000"
  volumes:
    - ./backend:/backend
  environment:
    - DB_PASSWORD=jupiter
    - DB_USER=jupiter
    - DB_HOST=db
    - DB_PORT=6000
    - MIGRATE=true
    - COLLECTSTATIC=true
    - TEST=false
    - RUNSERVER=false
    - SLEEP=true
  links:
    - db:db

frontend:
  image: jupiterapp/frontend
  ports:
    - "80:80"
  volumes:
    - ./frontend/app/:/frontend/app/
    - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./frontend/nginx/conf.d/:/etc/nginx/conf.d/
  links:
    - backend:backend