# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(max_length=30)),
                ('passport_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('passport_expires', models.DateField()),
                ('birth_date', models.DateField()),
                ('family_status', models.TextField()),
                ('dependants', models.TextField()),
                ('income', models.TextField()),
                ('realty', models.TextField()),
                ('job', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='profile',
                                              to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
                'permissions': (
                    ('view_user', 'Can view users'),
                    ('manage_himself', 'Can manage himself')
                ),
            },
        ),
    ]
