# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20161119_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposittemplate',
            name='duration',
        ),
        migrations.AddField(
            model_name='deposittemplate',
            name='additional_contributions',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
