# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 21:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_migrate_20161119_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credittemplate',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='credittemplate',
            name='max_amount_currency',
        ),
        migrations.RemoveField(
            model_name='credittemplate',
            name='min_amount_currency',
        ),
        migrations.RemoveField(
            model_name='credittemplate',
            name='monthly_payment',
        ),
        migrations.RemoveField(
            model_name='credittemplate',
            name='monthly_payment_currency',
        ),
        migrations.RemoveField(
            model_name='credittemplate',
            name='percentage',
        ),
        migrations.AddField(
            model_name='credittemplate',
            name='annual_percentage_rate',
            field=models.DecimalField(decimal_places=3, default=18, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credittemplate',
            name='max_amount',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='credittemplate',
            name='min_amount',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
