# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 22:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20161119_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittemplate',
            name='min_amount',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
