# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_credittemplate_min_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittemplate',
            name='max_duration',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
