# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_credittemplate_max_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='next_payment_temp',
            new_name='next_payment_term',
        ),
        migrations.AlterField(
            model_name='credittemplate',
            name='issue_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credittemplate',
            name='max_duration',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='deposittemplate',
            name='additional_contributions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deposittemplate',
            name='cancellation_condition',
            field=models.IntegerField(choices=[(0, 'Anytime'), (1, 'Anytime with lossy'), (2, 'Only after end of term')], default=1),
        ),
        migrations.AlterField(
            model_name='deposittemplate',
            name='indexing',
            field=models.IntegerField(choices=[(0, 'Yearly'), (1, 'Daily'), (2, 'Monthly'), (3, 'Quarterly')], default=0),
        ),
        migrations.AlterField(
            model_name='deposittemplate',
            name='prolongation',
            field=models.BooleanField(default=False),
        ),
    ]
