# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20161120_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='fine_percentage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='credittemplate',
            name='annual_percentage_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='credittemplate',
            name='fine_percentage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
