# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 17:05
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20161123_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittemplate',
            name='max_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency=b'BYN', max_digits=15, null=True),
        ),
    ]
