# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_auto_20161123_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposittemplate',
            old_name='percentage',
            new_name='currency',
        ),
        migrations.RemoveField(
            model_name='deposittemplate',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='deposittemplate',
            name='max_amount_currency',
        ),
        migrations.RemoveField(
            model_name='deposittemplate',
            name='min_amount',
        ),
        migrations.RemoveField(
            model_name='deposittemplate',
            name='min_amount_currency',
        ),
    ]
